"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-11

Bootstraps the schema by delegating to SQLModel.metadata.create_all(). This
keeps the first migration idempotent + matches whatever the current model
tree looks like. Subsequent migrations should be generated by
`alembic revision --autogenerate` and stop delegating.
"""
from typing import Sequence, Union

from alembic import op
from sqlmodel import SQLModel

# Ensure all model modules are imported so metadata is populated.
from app import models  # noqa: F401


revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    SQLModel.metadata.create_all(bind)


def downgrade() -> None:
    bind = op.get_bind()
    SQLModel.metadata.drop_all(bind)
